### ISSUE TITLE
Can't download releases from Github now either

### ISSUE THREAD

**Issue by Skrell** [CHEF-KOCH/dnscrypt-proxy-blacklist-filter#9]
I think your filters are blocking anything hosted on amazonaws

**Comment by Cade66** [comment]
Indeed `amazonaws.com` must imperatively be removed, makes no sens. Several specific `amazonaws.com` filters exist.
I'm surprised this hasn't been done yet, 16 days later. Until it is fixed I pause using this blacklist.
Security/privacy is one thing, bazaar another. Filters must be reliable, this blacklist isn't at this time.
Not to mention another absurdity : `ccmbg.com` which blocks correct page display of ccm.net for instance.
Please be careful with these blacklists because whitelisting a blacklisted domain is not the solution because doing so blocks as well the other legitimate blacklisted occurrences of the domain, making everyone lose time.

**Comment by CHEF-KOCH** [comment]
Well, critic is fine but I do not understand why you not just created a pull request? You cannot expect from a single person to maintain such a huge list without any problems (it's normal that there are false positives). 

That's the entire point of open source it, so that people can see the list and report their findings or submit their pull requests.

**Comment by Cade66** [comment]
I would have thought that pull requests were meant to address an issue on code, not on data.
But before all I'm a novice and i admit that I bring critics, good and bad, only from that perspective.
This said, of course mistakes exist, moreover when a project is maintained by one only and that the data is more than a mere 3 lines.
I was surprised the issue hadn't been replied to (and corrected) some two weeks after having been notified but, again, if said straightforwardly, had no implicit form of aggression.
I appreciate this work, your work, together with that of several other blacklists, all merged to enlighten dnscrypt-proxy. But nowadays a user committed to his privacy has so much to do (and most fortunately helped by developers) that getting on a hiccup because of a mistake may lead to frustration when the mistake takes time to be corrected.  I'm aware no one is at the service of anyone; I just thought I'd say my word, frankly :=)
